name: learn github actions 

### the on defines the trigger 
on:
    push: 
        branches:
            - main
          
    workflow_dispatch:        
        

jobs: 

    myfirstjob:
        runs-on: ubuntu-latest
        steps:
            - name: clone my repository 
              uses: actions/checkout@v4

 ### configure maven and setup maven integration with github actions.    
            - name: setup java and maven
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'       
              

       

